baseURL = 'http://stu-cc.it/'
languageCode = 'it-IT'
title = 'Caminoli Coppola Architetti'
theme = "scratch"
paginate = '8'

[menu]
    [[menu.main]]
    identifier = 'progetti'
    name = 'Progetti'
    title = 'progetti section'
    url = '/progetti/'
    weight = 2

    [[menu.main]]
    identifier = 'persone'
    name = 'Persone'
    title = 'persone section'
    url = '/persone/'
    weight = 3

    [[menu.main]]
    identifier = 'Contatti'
    name = 'Contatti'
    title = 'Contatti section'
    url = '/Contatti/'
    weight = 4


[params]
imageSrcset = [320, 640, 1280, 1600, 2000, 3000]
description = "Lo studio Caminoli Coppola inizia nel 1998 la collaborazione, dedicandosi alla ristrutturazione e al consolidamento di edifici storici come ville, masserie, case coloniche, palazzine. Negli anni più recenti lo studio si è dedicato anche a nuove costruzioni, principalmente in Toscana ed in Puglia."